### PR TITLE
Update CallEventType.cs

### PR DESCRIPTION
**Pull request by bfranklin825**
Perhaps I should have waited. I found another missing Call Event Type.

### CODE REVIEW

**Comment by lordmilko** [comment]
Can you please amend your previous commit to also increment the version to 0.3.2 (as was done for 0.3.1)

**Review by lordmilko — CHANGES_REQUESTED** [review]
Can you potentially request call logs for a much larger period than you are now (potentially using the `StreamSearch` method to allow retrieving a much larger result) and confirm whether there are any other call event types your server knows about that SwitchvoxAPI doesn't? (Since `StreamSearch` returns an `IEnumerable`, you'll obviously need to make sure you `ToList()` it to enumerate results)

**Review by lordmilko — CHANGES_REQUESTED** [review]
This should be 0.3.1. AppVeyor will increment this to 0.3.2 when it builds for Release

**Comment by bfranklin825** [comment]
I'll see if I can pull a ton of stuff tomorrow to see if I can ferret out some more call event types.

**Comment by lordmilko** [comment]
Thanks! If you add any more, no need to update the version number again

**Comment by lordmilko** [comment]
I have managed to extract what appears to be the definitive list of event types from the Switchvox web server files. I have also used this opportunity to reorganize the types listed in the file, which will likely replace this pull request.

There are two types I am not sure the meaning of however, *TC_ASSISTED_TRANSFER* and *TC_BLIND_TRANSFER*. I have opened a support case with Digium to ascertain what the difference between the TC and non-TC variants of these types are. Once I have received a response I will be able to release SwitchvoxAPI 0.3.2

If you have any idea what TC might stand for that would be very helpful!

Regards,
lordmilko

**Comment by lordmilko** [comment]
If you can use the [latest build](https://ci.appveyor.com/api/projects/lordmilko/switchvoxapi/artifacts/SwitchvoxAPI/bin/Release/SwitchvoxAPI.zip) when you do your test tomorrow that will give us a good indication as to whether this has resolved this issue

**Pull request closed without merging**
