### PR TITLE
Added methods "users.call" and "users.getMyInfo".

### PR DESCRIPTION
**Pull request by spider-bkv**

### CODE REVIEW

**Comment by lordmilko** [comment]
Hi @spider-bkv,

Thanks for this pull request. I am currently reviewing these changes to confirm everything looks good.

As I no longer have access to a Digium Switchvox system, I don't have the ability to independently verify any submissions to this repository work as expected. Are you able to confirm you've tested this against your environment and that it produces the expected results?

**Comment by lordmilko** [comment]
In addition since I see you added an `XmlRoot` attribute to the `ExtensionInfo` class, can you also confirm whether method `client.Extensions.GetInfo` still works when authenticated as an admin user?

**Comment by spider-bkv** [comment]
> In addition since I see you added an `XmlRoot` attribute to the `ExtensionInfo` class, can you also confirm whether method `client.Extensions.GetInfo` still works when authenticated as an admin user?

I confirm it works properly for me, I checked it as an admin user.

Thank you!

**Comment by lordmilko** [comment]
Hi @spider-bkv,

Please be advised SwitchvoxAPI 0.3.3 is now available to download from NuGet.

Please let me know if you have any further issues

Regards,
lordmilko

**Comment by spider-bkv** [comment]
Thank you so much for so fast updating NuGet package! I wouldn't even expected it to get so soon!

> Hi @spider-bkv,

> As I no longer have access to a Digium Switchvox system, I don't have the ability to independently verify any submissions to this repository work as expected. Are you able to confirm you've tested this against your environment and that it produces the expected results?

Regarding this part, I missed it in the very begging. Yes, I definitely confirm it. No worries, unfortunately, I have an access to Digium Switchvox on my project and I'm going to work with it very close next few months because it's our main IVR system.

So I think it's not a final commit. :)

Thanks again! And be well!

**Pull request merged**
